### PR TITLE
Remove unneeded files and relocate vignettes

### LINKED ISSUE #35: Bugfix: Unravel Remaining Interdependencies
## Expected Behavior
gsm.core cannot reference any other gsm packages in anything that is heading to CRAN.

## Current Behavior
These things have interconnections to other gsm packages:
- `dfGroups` docs. This arg only appears in `MakeWideGroups()`, which doesn't appear to be used anywhere anymore (see [this search](https://github.com/search?q=org%3AGilead-BioStats+MakeWideGroups&type=code)).
- `dfResults` docs. Similar. It isn't actually used in *any* gsm.core functions, though.
- `dfMetrics`, `lMetric`. Not actually used in gsm.core.
- `dfBounds`. Oh, hey! This one is actually produced here! Its help mentions the other dfs and other packages, but I don't think it NEEDS to do so. 
- `Cookbook.Rmd`. This can't live in gsm.core. If we aren't ready to migrate it to openrbqm, we can move it to an *article* in gsm.core, but it can't be in the CRAN package.
- `gsmExtensions.Rmd`. This technically *can* be in gsm.core, but it references other packages, so it's probably safest to make it an article.
- `DataAnalysis.Rmd`. Again, this one doesn't actually LOAD things from other packages, but it references them. It might be best to move *all* of the vignettes to articles (ie pkgdown-only).
- `DataModel.Rmd`. This one has lots of references to other packages, but it's referenced all over the place in docs. Maybe make the references links to the website?

## Possible Solution
Mostly delete. Some moving of things to article, and then a handful of actual edits.

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by lauramaxwell**
## Overview

Remove unnecessary glossary files and moved most vignettes to articles. Updated references to vignettes to link to pkgdown site instead of using `vignettes()`.

## Connected Issues

- Closes #35

### CODE REVIEW

File: R/Analyze_Fisher.R [hunk 1]
```diff
@@ -24,9 +24,9 @@
 #'
 #' @param dfTransformed `data.frame` Transformed data for analysis. Data should
 #'   have one record per site with expected columns: `GroupID`, `GroupLevel`,
-#'   `Numerator`, `Denominator`, and `Metric`. For more details see the Data
-#'   Model vignette: `vignette("DataModel", package = "gsm.core")`. For this
-#'   function, `dfTransformed` should typically be created using
+#'   `Numerator`, `Denominator`, and `Metric`. For more details see the
+#'   \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}.
```
Comment (jonthegeek) [inline R/Analyze_Fisher.R:28]:
```suggestion
#'   [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html).
```
We can use markdown in help. That will make it easier to update it when we change it to openrbqm, for example. I don't want to call it a vignette in case a CRAN reviewer freaks out about it.

File: R/Analyze_Identity.R [hunk 2]
```diff
@@ -11,9 +11,9 @@
 #'
 #' @param dfTransformed `data.frame` Transformed data for analysis. Data should
 #'   have one record per site with expected columns: `GroupID`, `GroupLevel`,
-#'   `Numerator`, `Denominator`, and `Metric`. For more details see the Data
-#'   Model vignette: `vignette("DataModel", package = "gsm.core")`. For this
-#'   function, `dfTransformed` should typically be created using
+#'   `Numerator`, `Denominator`, and `Metric`. For more details see the
+#'   \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}.
```
Comment (jonthegeek) [inline R/Analyze_Identity.R:15]:
```suggestion
#'   [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html).
```

File: R/Analyze_NormalApprox.R [hunk 3]
```diff
@@ -17,9 +17,9 @@
 #'
 #' @param dfTransformed `data.frame` Transformed data for analysis. Data should
 #'   have one record per site with expected columns: `GroupID`, `GroupLevel`,
-#'   `Numerator`, `Denominator`, and `Metric`. For more details see the Data
-#'   Model vignette: `vignette("DataModel", package = "gsm.core")`. For this
-#'   function, `dfTransformed` should typically be created using
+#'   `Numerator`, `Denominator`, and `Metric`. For more details see the
+#'   \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}.
```
Comment (jonthegeek) [inline R/Analyze_NormalApprox.R:21]:
```suggestion
#'   [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html)}.
```

File: R/Analyze_NormalApprox_PredictBounds.R [hunk 4]
```diff
@@ -14,9 +14,9 @@
 #'
 #' @param dfTransformed `data.frame` Transformed data for analysis. Data should
 #'   have one record per site with expected columns: `GroupID`, `GroupLevel`,
-#'   `Numerator`, `Denominator`, and `Metric`. For more details see the Data
-#'   Model vignette: `vignette("DataModel", package = "gsm.core")`. For this
-#'   function, `dfTransformed` should typically be created using
+#'   `Numerator`, `Denominator`, and `Metric`. For more details see the
+#'   \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}.
```
Comment (jonthegeek) [inline R/Analyze_NormalApprox_PredictBounds.R:18]:
```suggestion
#'   [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html).
```

File: R/Analyze_Poisson.R [hunk 5]
```diff
@@ -19,9 +19,9 @@
 #'
 #' @param dfTransformed `data.frame` Transformed data for analysis. Data should
 #'   have one record per site with expected columns: `GroupID`, `GroupLevel`,
-#'   `Numerator`, `Denominator`, and `Metric`. For more details see the Data
-#'   Model vignette: `vignette("DataModel", package = "gsm.core")`. For this
-#'   function, `dfTransformed` should typically be created using
+#'   `Numerator`, `Denominator`, and `Metric`. For more details see the
+#'   \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}.
```
Comment (jonthegeek) [inline R/Analyze_Poisson.R:23]:
```suggestion
#'   [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html).
```

File: R/Analyze_Poisson_PredictBounds.R [hunk 6]
```diff
@@ -16,7 +16,7 @@
 #' @param dfTransformed `data.frame` Transformed data for analysis. Data should
 #'   have one record per site with expected columns: `GroupID`, `GroupLevel`,
 #'   `Numerator`, `Denominator`, and `Metric`. For more details see the Data
```
Comment (jonthegeek) [inline R/Analyze_Poisson_PredictBounds.R:18]:
```suggestion
#'   `Numerator`, `Denominator`, and `Metric`. For more details see the [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html).
```
I couldn't leave this comment across lines 18 and 19, sadly.

File: R/Analyze_Poisson_PredictBounds.R [hunk 7]
```diff
@@ -16,7 +16,7 @@
...
-#'   Model vignette: `vignette("DataModel", package = "gsm.core")`. For this
+#'   Model vignette: \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}. For this
```
Comment (jonthegeek) [inline R/Analyze_Poisson_PredictBounds.R:19]:
```suggestion
#'   For this
```

File: R/Flag.R [hunk 8]
```diff
@@ -8,7 +8,7 @@
 #'
 #' @details
 #' This function provides a generalized framework for flagging sites as part of the
-#' GSM data model (see `vignette("DataModel", package = "gsm.core")`).
+#' GSM data model (see \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}).
```
Comment (jonthegeek) [inline R/Flag.R:11]:
```suggestion
#' GSM data model (see the [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html)).
```

File: R/RunStep.R [hunk 9]
```diff
@@ -31,7 +31,8 @@
 #' @param lStep `list` single workflow step (typically pulled from `lWorkflow$steps`). Should
 #'   include the name of the function to run (`lStep$name`), name of the object where the function result should be saved (`lStep$output`) and configurable parameters (`lStep$params`) (if any)
 #' @param lData `list` a named list of domain level data frames.
-#' @param lSpec `list` a data specification containing required columns. See `vignette("gsmExtensions", package = "gsm.core")`.
+#' @param lSpec `list` a data specification containing required columns. See the
+#'  \href{https://gilead-biostats.github.io/gsm.core/articles/gsmExtensions.html}{gsm Extensions Vignette}.
```
Comment (jonthegeek) [inline R/RunStep.R:35]:
```suggestion
#'  [gsm Extensions Vignette](https://gilead-biostats.github.io/gsm.core/articles/gsmExtensions.html).
```

File: R/aaa-shared.R [hunk 10]
```diff
@@ -8,8 +8,8 @@
 #'   reporting. Created by passing an `lWorkflow` object to [gsm.reporting::MakeMetric()].
 #'   Expected columns: `File`, `MetricID`, `Group`, `Abbreviation`, `Metric`,
 #'   `Numerator`, `Denominator`, `Model`, `Score`, and `Threshold`. For more
-#'   details see the Data Model vignette: `vignette("DataModel", package =
-#'   "gsm.core")`.
+#'   details see the
+#'   \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}..
```
Comment (jonthegeek) [inline R/aaa-shared.R:12]:
```suggestion
#'   [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html).
```

File: R/aaa-shared.R [hunk 11]
```diff
@@ -31,8 +31,8 @@
 #'   reporting. Created by passing an `lWorkflow` object to [gsm.reporting::MakeMetric()] and
 #'   turing it into a list. Expected columns: `File`,`MetricID`, `Group`,
 #'   `Abbreviation`, `Metric`, `Numerator`, `Denominator`, `Model`, `Score`, and
-#'   `strThreshold`. For more details see the Data Model vignette:
-#'   `vignette("DataModel", package = "gsm.core")`.
+#'   `strThreshold`. For more details see the
+#'   \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}.
```
Comment (jonthegeek) [inline R/aaa-shared.R:35]:
```suggestion
#'   [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html).
```

File: vignettes/articles/DataModel.Rmd [hunk 12]
```diff
@@ -40,7 +40,7 @@ In general, the `{gsm}` suite of packages is designed to be flexible and customi
...
 
-There is not a single data standard for raw or mapped data in `{gsm.mapping}`. The only requirement is that the mapped data is compatible with the analytics pipeline. Data Mapping transformations can be done using multiple methods including custom R scripts (e.g., with `dplyr`), SQL queries, or using `gsm.mapping` workflows (e.g. the `system.file("workflow/1_mapping/AE.yaml", package = "gsm.mapping")` file). Examples of these methods can be found in `vignette("Cookbook")`.
+There is not a single data standard for raw or mapped data in `{gsm.mapping}`. The only requirement is that the mapped data is compatible with the analytics pipeline. Data Mapping transformations can be done using multiple methods including custom R scripts (e.g., with `dplyr`), SQL queries, or using `gsm.mapping` workflows (e.g. the `system.file("workflow/1_mapping/AE.yaml", package = "gsm.mapping")` file). Examples of these methods can be found in the \href{https://gilead-biostats.github.io/gsm.core/articles/Cookbook.html}{Cookbook}.
```
Comment (jonthegeek) [inline vignettes/articles/DataModel.Rmd:43]:
```suggestion
There is not a single data standard for raw or mapped data in `{gsm.mapping}`. The only requirement is that the mapped data is compatible with the analytics pipeline. Data Mapping transformations can be done using multiple methods including custom R scripts (e.g., with `dplyr`), SQL queries, or using `gsm.mapping` workflows (e.g. the `system.file("workflow/1_mapping/AE.yaml", package = "gsm.mapping")` file). Examples of these methods can be found in the [Cookbook](https://gilead-biostats.github.io/gsm.core/articles/Cookbook.html).
```

**Review by jonthegeek — APPROVED** [review]
I made some tweaks, so commit those, and optionally redocument. I'm definitely going to redocument in #34, though, so I wouldn't worry about that. Still to-do (but I can apply it in #34): Make sure we're consistent about how we refer to gsm as a whole, and probably always put it in '' so CRAN doesn't flag it (they're a stickler about that in DESCRIPTIONs, I can't remember if they ever flag abbreviations in docs; I'll see if I can find specifics about that before standardizing everywhere).

File: R/Analyze_Fisher.R (hunk 1 above)
Comment (lauramaxwell) [reply R/Analyze_Fisher.R:28]: yeah- partway through i switched to this format. weird old latex habit crept in here for some reason 🙃

File: man/glossary/lMetric.yaml [hunk 13]
```diff
@@ -4,5 +4,5 @@ definition: >
   passing an `lWorkflow` object to [MakeMetric()] and turing it into a list.
   Expected columns: `File`,`MetricID`, `Group`, `Abbreviation`, `Metric`,
   `Numerator`, `Denominator`, `Model`, `Score`, and `strThreshold`.
-  For more details see the Data Model vignette:
-  `vignette("DataModel", package = "gsm.core")`.
+  For more details see the
+  \href{https://gilead-biostats.github.io/gsm.core/articles/DataModel.html}{Data Model Vignette}.
```
Comment (lauramaxwell) [inline man/glossary/lMetric.yaml:8]:
```suggestion
  [Data Model article](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html).
```

File: vignettes/articles/gsmExtensions.Rmd [hunk 14]
```diff
@@ -17,7 +17,7 @@ knitr::opts_chunk$set(
...
+This vignette describes how to extend `{gsm.core}` by creating new "modules", including metrics, reports and shiny apps that can be run using the standard `gsm` pipeline described in these articles: [Data Analysis](https://gilead-biostats.github.io/gsm.core/articles/DataAnalysis.html) and  [DataReporting](https://gilead-biostats.github.io/gsm.reporting/articles/DataReporting.html). As shown in the [Data Analysis article](https://gilead-biostats.github.io/gsm.core/articles/DataAnalysis.html), the existing `gsm` data pipeline can be used to capture a monitoring 'snapshot' for a study that includes a variety of "modules" including [metrics](https://github.com/Gilead-BioStats/gsm.mapping/tree/dev/inst/workflow/metrics/kri0001.yaml) and [reports](https://github.com/Gilead-BioStats/gsm.kri/blob/dev/inst/workflow/reports/report_kri_site.yaml).
```
Comment (lauramaxwell) [inline vignettes/articles/gsmExtensions.Rmd:20]:
```suggestion
This article describes how to extend `{gsm.core}` by creating new "modules", including metrics, reports and shiny apps that can be run using the standard `gsm` pipeline described in these articles: [Data Analysis](https://gilead-biostats.github.io/gsm.core/articles/DataAnalysis.html) and  [DataReporting](https://gilead-biostats.github.io/gsm.reporting/articles/DataReporting.html). As shown in the [Data Analysis article](https://gilead-biostats.github.io/gsm.core/articles/DataAnalysis.html), the existing `gsm` data pipeline can be used to capture a monitoring 'snapshot' for a study that includes a variety of "modules" including [metrics](https://github.com/Gilead-BioStats/gsm.mapping/tree/dev/inst/workflow/metrics/kri0001.yaml) and [reports](https://github.com/Gilead-BioStats/gsm.kri/blob/dev/inst/workflow/reports/report_kri_site.yaml). 
```

File: vignettes/articles/gsmExtensions.Rmd [hunk 15]
```diff
@@ -17,7 +17,7 @@ knitr::opts_chunk$set(
...
+This vignette describes how to extend `{gsm.core}` by creating new "modules", including metrics, reports and shiny apps that can be run using the standard `gsm` pipeline described in these articles: [Data Analysis](https://gilead-biostats.github.io/gsm.core/articles/DataAnalysis.html) and  [DataReporting](https://gilead-biostats.github.io/gsm.reporting/articles/DataReporting.html). As shown in the [Data Analysis article](https://gilead-biostats.github.io/gsm.core/articles/DataAnalysis.html), the existing `gsm` data pipeline can be used to capture a monitoring 'snapshot' for a study that includes a variety of "modules" including [metrics](https://github.com/Gilead-BioStats/gsm.mapping/tree/dev/inst/workflow/metrics/kri0001.yaml) and [reports](https://github.com/Gilead-BioStats/gsm.kri/blob/dev/inst/workflow/reports/report_kri_site.yaml). 
 
 This vignette provide detailed specifications for creating new modules, a description of the directory structure for the yaml workflows that comprise a module pipeline, and links to resources that can be used to configure study-level gsm pipelines that utilize these extensions.
```
Comment (lauramaxwell) [inline vignettes/articles/gsmExtensions.Rmd:22]:
```suggestion
This article provides detailed specifications for creating new modules, a description of the directory structure for the yaml workflows that comprise a module pipeline, and links to resources that can be used to configure study-level gsm pipelines that utilize these extensions.
```
